apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      project: {{ .Release.Name }}
  template:
    metadata:
      name: {{ .Release.Name }}-template
      labels:
        project: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-image
          image: {{.Values.image}}
