apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  selector:
    project: {{ .Release.Name }}
  ports:
    - name: {{ .Release.Name }}-listener
      port: 80
      protocol: TCP
      targetPort: 80
  type: NodePort